sudo: false

language: node_js
node_js:
  - 9

branches:
  only:
    - master
    - develop

install:
  - npm install newman
  - npm install parcel-bundler
before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  # - node_modules/.bin/newman run POSTMAN_COLLECTIONS/crud_test_api.postman_collection.json  -e POSTMAN_COLLECTIONS/date_created.postman_environment.json -e POSTMAN_COLLECTIONS/comment.postman_environment.json -e POSTMAN_COLLECTIONS/number.postman_environment.json  -e POSTMAN_COLLECTIONS/date_supply.postman_environment.json -g POSTMAN_COLLECTIONS/global.postman_globals.json
  # - node_modules/.bin/newman run POSTMAN_COLLECTIONS/get_by_filter.postman_collection.json  -e POSTMAN_COLLECTIONS/comment.postman_environment.json -e POSTMAN_COLLECTIONS/number.postman_environment.json  -e POSTMAN_COLLECTIONS/date_supply.postman_environment.json -g POSTMAN_COLLECTIONS/global.postman_globals.json
  - npm run build 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master