sudo: false

language: node_js
node_js:
  - 9

branches:
  only:
    - master

install:
  - npm install newman

efore_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run POSTMAN_COLLECTIONS/crud test api.postman_collection.json  POSTMAN_COLLECTIONS/get by filter.postman_collection.json -e POSTMAN_COLLECTIONS/date_created.postman_environment.json -e POSTMAN_COLLECTIONS/comment.postman_environment.json -e POSTMAN_COLLECTIONS/number.postman_environment.json  -e POSTMAN_COLLECTIONS/date_supply.postman_environment.json -g POSTMAN_COLLECTIONS/global.postman_globals.json